# Generated by Django 5.1.7 on 2025-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='translated_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
