version: '3.8'
name: analytica20

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
