# Generated by Django 5.1.7 on 2025-03-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_autheticated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_id_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('handle', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(blank=True, default='NA', max_length=20)),
                ('toxicity', models.CharField(blank=True, default='NA', max_length=20)),
                ('emotion', models.CharField(blank=True, default='NA', max_length=20)),
            ],
        ),
    ]
