# Generated by Django 5.1.7 on 2025-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
